# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastros.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastros(object):
    def setupUi(self, Cadastros):
        Cadastros.setObjectName("Cadastros")
        Cadastros.resize(442, 406)
        self.centralwidget = QtWidgets.QWidget(Cadastros)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 60, 351, 291))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_name = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.lineEdit_new_user = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_new_user.setObjectName("lineEdit_new_user")
        self.verticalLayout.addWidget(self.lineEdit_new_user)
        self.lineEdit_new_password = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_new_password.setObjectName("lineEdit_new_password")
        self.verticalLayout.addWidget(self.lineEdit_new_password)
        self.lineEdit_repeat_password = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_repeat_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_repeat_password.setObjectName("lineEdit_repeat_password")
        self.verticalLayout.addWidget(self.lineEdit_repeat_password)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 341, 51))
        self.label.setObjectName("label")
        self.pushButton_apply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_apply.setGeometry(QtCore.QRect(90, 340, 251, 41))
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 47, 13))
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.frame.raise_()
        self.pushButton_apply.raise_()
        self.label_2.raise_()
        Cadastros.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cadastros)
        QtCore.QMetaObject.connectSlotsByName(Cadastros)

    def retranslateUi(self, Cadastros):
        _translate = QtCore.QCoreApplication.translate
        Cadastros.setWindowTitle(_translate("Cadastros", "Cadastros"))
        self.lineEdit_name.setPlaceholderText(_translate("Cadastros", "Digite seu nome"))
        self.lineEdit_new_user.setPlaceholderText(_translate("Cadastros", "Digite seu usuário"))
        self.lineEdit_new_password.setPlaceholderText(_translate("Cadastros", "Digite sua senha"))
        self.lineEdit_repeat_password.setPlaceholderText(_translate("Cadastros", "Repita sua senha"))
        self.label.setText(_translate("Cadastros", "Preencha os campos abaixo para cadastrar um novo usuário"))
        self.pushButton_apply.setText(_translate("Cadastros", "CADASTRAR"))
        self.label_2.setText(_translate("Cadastros", "ERROR"))
