# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(414, 454)
        font = QtGui.QFont()
        font.setPointSize(2)
        Login.setFont(font)
        Login.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_user = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_user.setGeometry(QtCore.QRect(100, 90, 221, 41))
        self.lineEdit_user.setStyleSheet("QLineEdit{\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(40,40,40);\n"
"    color: rbg(200,200,200);\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(66, 239, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(40,40,40);\n"
"}\n"
"QLineEdit:focus{\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(255,255,255);\n"
"    color: rbg(200,200,200);\n"
"}")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(100, 150, 221, 41))
        self.lineEdit_password.setStyleSheet("QLineEdit{\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(40,40,40)\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(66, 239, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(40,40,40);\n"
"}\n"
"QLineEdit:focus{\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(255,255,255);\n"
"}")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(100, 220, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(200,200,200)\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(66, 239, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(40,40,40);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(0, 111, 166);\n"
"    color: rgb(255,255,255);\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.label_retorune = QtWidgets.QLabel(self.centralwidget)
        self.label_retorune.setGeometry(QtCore.QRect(160, 280, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_retorune.setFont(font)
        self.label_retorune.setObjectName("label_retorune")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 390, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_signin = QtWidgets.QPushButton(self.centralwidget)
        self.btn_signin.setGeometry(QtCore.QRect(260, 380, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_signin.setFont(font)
        self.btn_signin.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(200,200,200)\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(66, 239, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(40,40,40);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(0, 111, 166);\n"
"    color: rgb(255,255,255);\n"
"}")
        self.btn_signin.setObjectName("btn_signin")
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.lineEdit_user.setPlaceholderText(_translate("Login", "USERNAME"))
        self.lineEdit_password.setPlaceholderText(_translate("Login", "PASSWORD"))
        self.btn_login.setText(_translate("Login", "LOGIN"))
        self.label_retorune.setText(_translate("Login", "Invalid User"))
        self.label_2.setText(_translate("Login", "Nâo possui cadastro?"))
        self.btn_signin.setText(_translate("Login", "SIGN IN"))
